export const sampleProducts = [
  {
    id: "balloon-1",
    name: "Birthday Balloons Pack",
    category: "Balloons",
    price: 12.99,
    discount: 15,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    ratingCount: 127,
    stock: 25,
    attributes: {
      occasion: ["Birthday", "Celebration"],
      type: "Latex",
      size: "Standard",
      color: "Multi-color",
      finish: "Metallic",
    },
  },
  {
    id: "balloon-2",
    name: "Giant Number Balloons",
    category: "Balloons",
    price: 24.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    ratingCount: 89,
    stock: 12,
    attributes: {
      occasion: ["Birthday"],
      type: "Foil",
      size: "Giant",
      color: "Gold",
      finish: "Metallic",
    },
  },
  {
    id: "balloon-3",
    name: "Wedding Balloons Set",
    category: "Balloons",
    price: 18.5,
    discount: 20,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    ratingCount: 56,
    stock: 8,
    attributes: {
      occasion: ["Wedding"],
      type: "Latex",
      size: "Standard",
      color: "White",
      finish: "Pearlescent",
    },
  },
  {
    id: "balloon-4",
    name: "LED Light-up Balloons",
    category: "Balloons",
    price: 15.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    ratingCount: 42,
    stock: 15,
    attributes: {
      occasion: ["Party", "Celebration"],
      type: "LED",
      size: "Standard",
      color: "Multi-color",
      finish: "Matte",
    },
  },
  {
    id: "balloon-5",
    name: "Confetti Balloons Set",
    category: "Balloons",
    price: 9.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    ratingCount: 78,
    stock: 30,
    attributes: {
      occasion: ["Birthday", "Party"],
      type: "Latex",
      size: "Standard",
      color: "Multi-color",
      finish: "Confetti",
    },
  },
  {
    id: "balloon-6",
    name: "Heart-shaped Foil Balloons",
    category: "Balloons",
    price: 14.99,
    discount: 10,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.4,
    ratingCount: 65,
    stock: 18,
    attributes: {
      occasion: ["Valentine's Day", "Anniversary"],
      type: "Foil",
      size: "Standard",
      color: "Red",
      finish: "Metallic",
    },
  },
  {
    id: "card-1",
    name: "Handmade Birthday Card",
    category: "Cards",
    price: 4.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    ratingCount: 215,
    stock: 50,
    attributes: {
      occasion: ["Birthday"],
      recipient: ["Friend", "Family"],
      style: "Handmade",
    },
  },
  {
    id: "card-2",
    name: "Wedding Congratulations Card",
    category: "Cards",
    price: 5.99,
    discount: 10,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    ratingCount: 78,
    stock: 30,
    attributes: {
      occasion: ["Wedding"],
      recipient: ["Friend", "Family"],
      style: "Artistic",
    },
  },
  {
    id: "card-3",
    name: "Thank You Cards Pack",
    category: "Cards",
    price: 8.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    ratingCount: 92,
    stock: 45,
    attributes: {
      occasion: ["Thank You"],
      recipient: ["Anyone"],
      style: "Modern",
    },
  },
  {
    id: "card-4",
    name: "Anniversary Card",
    category: "Cards",
    price: 6.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    ratingCount: 67,
    stock: 25,
    attributes: {
      occasion: ["Anniversary"],
      recipient: ["Partner"],
      style: "Romantic",
    },
  },
  {
    id: "card-5",
    name: "Get Well Soon Card",
    category: "Cards",
    price: 3.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    ratingCount: 45,
    stock: 35,
    attributes: {
      occasion: ["Get Well"],
      recipient: ["Friend", "Family"],
      style: "Cheerful",
    },
  },
  {
    id: "card-6",
    name: "New Baby Congratulations Card",
    category: "Cards",
    price: 5.49,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    ratingCount: 58,
    stock: 40,
    attributes: {
      occasion: ["New Baby"],
      recipient: ["Friend", "Family"],
      style: "Cute",
    },
  },
  {
    id: "home-1",
    name: "Decorative Wall Clock",
    category: "Home & Living",
    price: 34.99,
    discount: 25,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.3,
    ratingCount: 67,
    stock: 5,
    attributes: {
      subcategory: ["Clocks"],
      color: "Black",
      size: "Medium",
      brand: "HomeStyle",
    },
  },
  {
    id: "home-2",
    name: "Photo Frame Set",
    category: "Home & Living",
    price: 28.5,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    ratingCount: 93,
    stock: 18,
    attributes: {
      subcategory: ["Frames"],
      color: "White",
      size: "Medium",
      brand: "FrameIt",
    },
  },
  {
    id: "home-3",
    name: "Scented Candle Set",
    category: "Home & Living",
    price: 19.99,
    discount: 15,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    ratingCount: 112,
    stock: 22,
    attributes: {
      subcategory: ["Candles"],
      color: "Multi-color",
      size: "Standard",
      brand: "AromaHome",
    },
  },
  {
    id: "kitchen-1",
    name: "Ceramic Mug Set",
    category: "Kitchen & Dining",
    price: 22.99,
    discount: 15,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    ratingCount: 124,
    stock: 22,
    attributes: {
      type: ["Mugs"],
      material: "Ceramic",
      brand: "KitchenPro",
    },
  },
  {
    id: "kitchen-2",
    name: "Glass Serving Platter",
    category: "Kitchen & Dining",
    price: 32.5,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.4,
    ratingCount: 56,
    stock: 7,
    attributes: {
      type: ["Serveware"],
      material: "Glass",
      brand: "GlassWorks",
    },
  },
  {
    id: "kitchen-3",
    name: "Stainless Steel Cutlery Set",
    category: "Kitchen & Dining",
    price: 45.99,
    discount: 10,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    ratingCount: 87,
    stock: 15,
    attributes: {
      type: ["Cutlery"],
      material: "Stainless Steel",
      brand: "DineWell",
    },
  },
  {
    id: "toy-1",
    name: "Educational Puzzle Set",
    category: "Toys, Novelties & Collectibles",
    price: 19.99,
    discount: 20,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    ratingCount: 87,
    stock: 14,
    attributes: {
      ageGroup: ["3-5 years"],
      type: ["Puzzle", "Educational"],
      brand: "LearnPlay",
    },
  },
  {
    id: "toy-2",
    name: "Collectible Action Figure",
    category: "Toys, Novelties & Collectibles",
    price: 45.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    ratingCount: 134,
    stock: 3,
    attributes: {
      ageGroup: ["13+ years", "Adult"],
      type: ["Action Figure", "Collectible"],
      brand: "CollectiblesInc",
    },
  },
  {
    id: "toy-3",
    name: "Plush Teddy Bear",
    category: "Toys, Novelties & Collectibles",
    price: 15.99,
    discount: 0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    ratingCount: 98,
    stock: 25,
    attributes: {
      ageGroup: ["0-2 years", "3-5 years"],
      type: ["Plush"],
      brand: "ToyWorld",
    },
  },
]
